Remove unused files
- Change readme back to original fork

diff --git a/Dockerfile.template b/Dockerfile.template
--- a/Dockerfile.template
+++ b/Dockerfile.template
@@ -9,13 +9,13 @@ RUN install_packages dnsmasq wireless-tools
 # use latest version. If specific version is required, it should be provided as vX.Y.Z, e.g v4.11.37
 ARG VERSION="latest"
 
-# create /usr/src/app/ui directory where we will extract pre-built UI 
+# create /usr/src/app/ui directory where we will extract pre-built UI
 WORKDIR /usr/src/app/ui
 
 WORKDIR /usr/src/app
 
 RUN \
-    export BASE_URL="https://github.com/balena-os/wifi-connect/releases" &&\    
+    export BASE_URL="https://github.com/balena-os/wifi-connect/releases" &&\
     case $BALENA_ARCH in \
         "aarch64") \
             BINARY_ARCH_NAME="aarch64-unknown-linux-gnu" ;; \
@@ -24,7 +24,7 @@ RUN \
         "armv7hf") \
             BINARY_ARCH_NAME="armv7-unknown-linux-gnueabihf" ;;\
         *) \
-            echo >&2 "error: unsupported architecture ($BALENA_ARCH)"; exit 1 ;; \ 
+            echo >&2 "error: unsupported architecture ($BALENA_ARCH)"; exit 1 ;; \
     esac;\
     if [ ${VERSION} = "latest" ]; then \
         export URL_PARTIAL="latest/download" ; \
@@ -34,7 +34,7 @@ RUN \
     curl -Ls "$BASE_URL/$URL_PARTIAL/wifi-connect-$BINARY_ARCH_NAME.tar.gz" \
     | tar -xvz -C  /usr/src/app/ &&\
     curl -Ls "$BASE_URL/$URL_PARTIAL/wifi-connect-ui.tar.gz" \
-    | tar -xvz -C  /usr/src/app/ui 
+    | tar -xvz -C  /usr/src/app/ui
 
 COPY scripts/start.sh .
 
